{"name": "test_logout", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//*[@id=\"user-tools\"]/a[3]')\nStacktrace:\n#0 0x5587ecbb1403 <unknown>\n#1 0x5587ec9b7778 <unknown>\n#2 0x5587ec9eec87 <unknown>\n#3 0x5587ec9eee51 <unknown>\n#4 0x5587eca21f24 <unknown>\n#5 0x5587eca0ca2d <unknown>\n#6 0x5587eca1fc74 <unknown>\n#7 0x5587eca0c8f3 <unknown>\n#8 0x5587ec9e20d8 <unknown>\n#9 0x5587ec9e3205 <unknown>\n#10 0x5587ecbf8e3d <unknown>\n#11 0x5587ecbfbdb6 <unknown>\n#12 0x5587ecbe213e <unknown>\n#13 0x5587ecbfc9b5 <unknown>\n#14 0x5587ecbd6970 <unknown>\n#15 0x5587ecc19228 <unknown>\n#16 0x5587ecc193bf <unknown>\n#17 0x5587ecc33abe <unknown>\n#18 0x7f4354a6bb43 <unknown>", "trace": "self = <test_user_logout.TestLogout object at 0x7f816e0f3910>, login_page = <pages.Login_page.LoginPage object at 0x7f816e0f3cd0>\nbrowser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"81dd113282354871c4a048c8175c2d6e\")>\n\n    @allure.feature('UI tests')\n    @allure.story('Login new user in positive')\n    @pytest.mark.positive\n    def test_logout(self, login_page, browser):\n        with allure.step('Authorization steps in UI'):\n            login_user = LoginPage(browser)\n            login_user.fill_username_field(username)\n            login_user.fill_password_field(password)\n            login_user.click_login_field()\n            users_logout = User_Page_Logout(browser)\n>           users_logout.click_logout_field()\n\ntests/test_user_logout.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages/User_page_logout.py:13: in click_logout_field\n    field = self.find_element(User_Add_Locators.LOGOUT_LINK)\npages/Base_page.py:14: in find_element\n    message=f\"Can't find element by locator {locator}\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"81dd113282354871c4a048c8175c2d6e\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x7f816e061b00>, message = 'Can\\'t find element by locator (\\'xpath\\', \\'//*[@id=\"user-tools\"]/a[3]\\')'\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//*[@id=\"user-tools\"]/a[3]')\nE       Stacktrace:\nE       #0 0x5587ecbb1403 <unknown>\nE       #1 0x5587ec9b7778 <unknown>\nE       #2 0x5587ec9eec87 <unknown>\nE       #3 0x5587ec9eee51 <unknown>\nE       #4 0x5587eca21f24 <unknown>\nE       #5 0x5587eca0ca2d <unknown>\nE       #6 0x5587eca1fc74 <unknown>\nE       #7 0x5587eca0c8f3 <unknown>\nE       #8 0x5587ec9e20d8 <unknown>\nE       #9 0x5587ec9e3205 <unknown>\nE       #10 0x5587ecbf8e3d <unknown>\nE       #11 0x5587ecbfbdb6 <unknown>\nE       #12 0x5587ecbe213e <unknown>\nE       #13 0x5587ecbfc9b5 <unknown>\nE       #14 0x5587ecbd6970 <unknown>\nE       #15 0x5587ecc19228 <unknown>\nE       #16 0x5587ecc193bf <unknown>\nE       #17 0x5587ecc33abe <unknown>\nE       #18 0x7f4354a6bb43 <unknown>\n\nvenw/lib/python3.7/site-packages/selenium/webdriver/support/wait.py:89: TimeoutException"}, "steps": [{"name": "Authorization steps in UI", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Can't find element by locator ('xpath', '//*[@id=\"user-tools\"]/a[3]')\nStacktrace:\n#0 0x5587ecbb1403 <unknown>\n#1 0x5587ec9b7778 <unknown>\n#2 0x5587ec9eec87 <unknown>\n#3 0x5587ec9eee51 <unknown>\n#4 0x5587eca21f24 <unknown>\n#5 0x5587eca0ca2d <unknown>\n#6 0x5587eca1fc74 <unknown>\n#7 0x5587eca0c8f3 <unknown>\n#8 0x5587ec9e20d8 <unknown>\n#9 0x5587ec9e3205 <unknown>\n#10 0x5587ecbf8e3d <unknown>\n#11 0x5587ecbfbdb6 <unknown>\n#12 0x5587ecbe213e <unknown>\n#13 0x5587ecbfc9b5 <unknown>\n#14 0x5587ecbd6970 <unknown>\n#15 0x5587ecc19228 <unknown>\n#16 0x5587ecc193bf <unknown>\n#17 0x5587ecc33abe <unknown>\n#18 0x7f4354a6bb43 <unknown>\n\n", "trace": "  File \"/home/vadim/project/tms_prodject-main/tests/test_user_logout.py\", line 19, in test_logout\n    users_logout.click_logout_field()\n  File \"/home/vadim/project/tms_prodject-main/pages/User_page_logout.py\", line 13, in click_logout_field\n    field = self.find_element(User_Add_Locators.LOGOUT_LINK)\n  File \"/home/vadim/project/tms_prodject-main/pages/Base_page.py\", line 14, in find_element\n    message=f\"Can't find element by locator {locator}\")\n  File \"/home/vadim/project/tms_prodject-main/venw/lib/python3.7/site-packages/selenium/webdriver/support/wait.py\", line 89, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1660743485456, "stop": 1660743491557}], "start": 1660743485455, "stop": 1660743491560, "uuid": "f6f0dda5-11c0-4233-a135-8146d3beb24e", "historyId": "a7f9f22a65adc13bd22ba693b4c270e1", "testCaseId": "6b256e0c7a5e9b3f2aaed248df4f10ef", "fullName": "tests.test_user_logout.TestLogout#test_logout", "labels": [{"name": "story", "value": "Login new user in positive"}, {"name": "feature", "value": "UI tests"}, {"name": "tag", "value": "positive"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_logout"}, {"name": "subSuite", "value": "TestLogout"}, {"name": "host", "value": "vadim-X756UQK"}, {"name": "thread", "value": "35129-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_logout"}]}